
required-version = "==0.16.9"
target-version = "py312"

[lint.flake8-bugbear]
# FastAPI's Depends()/Query() in default arguments, ignore B008 function-call-in-default-argument 
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]