"""Create 'trips' and 'trip_excluded_pois' tables

Revision ID: 17fcf1b3a1eb
Revises: 78845eb678e0
Create Date: 2026-07-11 00:47:15.762141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17fcf1b3a1eb'
down_revision: Union[str, Sequence[str], None] = '78845eb678e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('pace', sa.String(length=20), nullable=True),
    sa.Column('excluded_poi_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_conversation_id'), 'trips', ['conversation_id'], unique=True)
    op.create_table('trip_excluded_pois',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_id', 'poi_id')
    )
    op.create_index(op.f('ix_trip_excluded_pois_poi_id'), 'trip_excluded_pois', ['poi_id'], unique=False)
    op.create_index(op.f('ix_trip_excluded_pois_trip_id'), 'trip_excluded_pois', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_trip_excluded_pois_trip_id'), table_name='trip_excluded_pois')
    op.drop_index(op.f('ix_trip_excluded_pois_poi_id'), table_name='trip_excluded_pois')
    op.drop_table('trip_excluded_pois')
    op.drop_index(op.f('ix_trips_conversation_id'), table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
