"""initial schema

Revision ID: 2e31d4460e80
Revises: 
Create Date: 2026-06-20 09:17:36.001401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e31d4460e80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('landmark', 'museum', 'viewpoint', 'market', 'park', 'gallery', 'neighborhood', 'other', name='poi_type'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('borough', sa.String(length=50), nullable=False),
    sa.Column('neighborhood', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('hero_image_url', sa.String(length=2048), nullable=True),
    sa.Column('gallery_image_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opening_hours_text', sa.String(length=100), nullable=True),
    sa.Column('google_place_id', sa.String(length=255), nullable=True),
    sa.Column('google_review_star', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('google_review_count', sa.Integer(), nullable=True),
    sa.Column('current_busyness', sa.Enum('quiet', 'moderate', 'busy', 'very_busy', name='busyness_level'), nullable=True),
    sa.Column('current_busyness_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('best_time_start', sa.Time(), nullable=True),
    sa.Column('best_time_end', sa.Time(), nullable=True),
    sa.Column('best_time_label', sa.Text(), nullable=True),
    sa.Column('why_this_time', sa.Text(), nullable=True),
    sa.Column('accessibility_labels', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('admission_fee', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('admission_text', sa.Text(), nullable=True),
    sa.Column('recommended_duration_min', sa.Integer(), nullable=True),
    sa.Column('closest_subway', sa.String(length=100), nullable=True),
    sa.Column('map_embed_url', sa.String(length=2048), nullable=True),
    sa.Column('map_external_url', sa.String(length=2048), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("borough IN ('Manhattan','Brooklyn','Queens','Bronx','Staten Island')"),
    sa.CheckConstraint('google_review_count >= 0'),
    sa.CheckConstraint('google_review_star BETWEEN 0 AND 5'),
    sa.CheckConstraint('latitude  BETWEEN -90  AND 90'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180'),
    sa.CheckConstraint('recommended_duration_min > 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_borough'), 'poi', ['borough'], unique=False)
    op.create_index(op.f('ix_poi_slug'), 'poi', ['slug'], unique=True)
    op.create_index(op.f('ix_poi_type'), 'poi', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('saved_pois',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.BigInteger(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'poi_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_sessions')
    op.drop_table('saved_pois')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_poi_type'), table_name='poi')
    op.drop_index(op.f('ix_poi_slug'), table_name='poi')
    op.drop_index(op.f('ix_poi_borough'), table_name='poi')
    op.drop_table('poi')
    # ### end Alembic commands ###
