"""Create itinerary_stops table

Revision ID: 442f6de0bbd6
Revises: e432bd247a50
Create Date: 2026-07-08 23:53:19.846655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '442f6de0bbd6'
down_revision: Union[str, Sequence[str], None] = 'e432bd247a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.BigInteger(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('dates', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=20), nullable=False),
    sa.Column('slot_start', sa.Time(), nullable=False),
    sa.Column('slot_end', sa.Time(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('crowd_level', sa.String(length=20), nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('busyness_for_day', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_added', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['saved_itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('saved_itineraries', 'itinerary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_itineraries', sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_table('itinerary_stops')
    # ### end Alembic commands ###
