"""add saved pois

Revision ID: 561099b79357
Revises: fcfb9195881b
Create Date: 2026-06-17 22:36:15.254821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '561099b79357'
down_revision: Union[str, Sequence[str], None] = 'fcfb9195881b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_poi_borough'), table_name='poi')
    op.drop_index(op.f('idx_poi_geo'), table_name='poi')
    op.drop_index(op.f('idx_poi_tags'), table_name='poi', postgresql_using='gin')
    op.drop_index(op.f('idx_poi_type'), table_name='poi')
    op.drop_table('poi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('landmark', 'museum', 'viewpoint', 'market', 'park', 'gallery', 'neighborhood', 'other', name='poi_type'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('borough', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('neighborhood', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hero_image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gallery_image_urls', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('opening_hours_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_place_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('google_review_star', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('google_review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_busyness', postgresql.ENUM('quiet', 'moderate', 'busy', 'very_busy', name='busyness_level'), autoincrement=False, nullable=True),
    sa.Column('current_busyness_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('best_time_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('best_time_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('best_time_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('why_this_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessibility_labels', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('admission_fee', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('admission_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_duration_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closest_subway', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_embed_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('map_external_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("borough = ANY (ARRAY['Manhattan'::text, 'Brooklyn'::text, 'Queens'::text, 'Bronx'::text, 'Staten Island'::text])", name=op.f('poi_borough_check')),
    sa.CheckConstraint("latitude >= '-90'::integer::double precision AND latitude <= 90::double precision", name=op.f('poi_latitude_check')),
    sa.CheckConstraint("longitude >= '-180'::integer::double precision AND longitude <= 180::double precision", name=op.f('poi_longitude_check')),
    sa.CheckConstraint('google_review_count >= 0', name=op.f('poi_google_review_count_check')),
    sa.CheckConstraint('google_review_star >= 0::numeric AND google_review_star <= 5::numeric', name=op.f('poi_google_review_star_check')),
    sa.CheckConstraint('recommended_duration_min > 0', name=op.f('poi_recommended_duration_min_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('poi_pkey')),
    sa.UniqueConstraint('google_place_id', name=op.f('poi_google_place_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name=op.f('poi_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_poi_type'), 'poi', ['type'], unique=False)
    op.create_index(op.f('idx_poi_tags'), 'poi', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_poi_geo'), 'poi', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_poi_borough'), 'poi', ['borough'], unique=False)
    # ### end Alembic commands ###
