"""Create user_itineraries table

Revision ID: 97a15f7350e7
Revises: a685b4a9286e
Create Date: 2026-07-09 12:01:16.607635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97a15f7350e7'
down_revision: Union[str, Sequence[str], None] = 'a685b4a9286e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('itinerary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_stops',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('itinerary_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('poi_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('slot', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('slot_start', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('slot_end', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('crowd_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('busyness_for_day', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('user_added', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('visit_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hero_image_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['saved_itineraries.id'], name=op.f('itinerary_stops_itinerary_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], name=op.f('itinerary_stops_poi_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('itinerary_stops_pkey'))
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('saved_itineraries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('saved_itineraries_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_itineraries_pkey'))
    )
    op.drop_table('user_itineraries')
    # ### end Alembic commands ###
