"""add token_version column to users table

Revision ID: 98f3ce1d730a
Revises: ee793910089d
Create Date: 2026-06-19 21:47:35.953427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98f3ce1d730a'
down_revision: Union[str, Sequence[str], None] = 'ee793910089d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_pois')
    op.drop_index(op.f('ix_pois_borough'), table_name='pois')
    op.drop_index(op.f('ix_pois_slug'), table_name='pois')
    op.drop_index(op.f('ix_pois_type'), table_name='pois')
    op.drop_table('pois')
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.create_table('pois',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('landmark', 'museum', 'viewpoint', 'market', 'park', 'gallery', 'neighborhood', 'other', name='poi_type'), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('borough', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('neighborhood', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hero_image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('gallery_image_urls', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('opening_hours_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('google_place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('google_review_star', sa.NUMERIC(precision=2, scale=1), autoincrement=False, nullable=True),
    sa.Column('google_review_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_busyness', postgresql.ENUM('quiet', 'moderate', 'busy', 'very_busy', name='busyness_level'), autoincrement=False, nullable=True),
    sa.Column('current_busyness_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('best_time_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('best_time_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('best_time_label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('why_this_time', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('accessibility_labels', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('admission_fee', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True),
    sa.Column('admission_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recommended_duration_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closest_subway', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('map_embed_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('map_external_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("borough::text = ANY (ARRAY['Manhattan'::character varying, 'Brooklyn'::character varying, 'Queens'::character varying, 'Bronx'::character varying, 'Staten Island'::character varying]::text[])", name=op.f('pois_borough_check')),
    sa.CheckConstraint("latitude >= '-90'::integer::double precision AND latitude <= 90::double precision", name=op.f('pois_latitude_check')),
    sa.CheckConstraint("longitude >= '-180'::integer::double precision AND longitude <= 180::double precision", name=op.f('pois_longitude_check')),
    sa.CheckConstraint('google_review_count >= 0', name=op.f('pois_google_review_count_check')),
    sa.CheckConstraint('google_review_star >= 0::numeric AND google_review_star <= 5::numeric', name=op.f('pois_google_review_star_check')),
    sa.CheckConstraint('recommended_duration_min > 0', name=op.f('pois_recommended_duration_min_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('pois_pkey'))
    )
    op.create_index(op.f('ix_pois_type'), 'pois', ['type'], unique=False)
    op.create_index(op.f('ix_pois_slug'), 'pois', ['slug'], unique=True)
    op.create_index(op.f('ix_pois_borough'), 'pois', ['borough'], unique=False)
    op.create_table('saved_pois',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('poi_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['pois.id'], name=op.f('saved_pois_poi_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('saved_pois_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'poi_id', name=op.f('saved_pois_pkey'))
    )
    # ### end Alembic commands ###
