"""Create POI Busyness Forecast table

Revision ID: 9b0d8a6c958c
Revises: 2e31d4460e80
Create Date: 2026-06-21 01:22:44.226961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '9b0d8a6c958c'
down_revision: Union[str, Sequence[str], None] = '2e31d4460e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_busyness_forecast',
    sa.Column('poi_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=False),
    sa.Column('busyness_pct', sa.SmallInteger(), nullable=False),
    sa.Column('level', ENUM(name='busyness_level', create_type=False)),
    sa.Column('source', sa.Text(), server_default=sa.text("'model'"), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('busyness_pct BETWEEN 0 AND 100'),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6'),
    sa.CheckConstraint('hour_of_day BETWEEN 0 AND 23'),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('poi_id', 'day_of_week', 'hour_of_day')
    )
    op.create_index('idx_forecast_level', 'poi_busyness_forecast', ['level'], unique=False)
    op.create_index('idx_forecast_poi', 'poi_busyness_forecast', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_forecast_poi', table_name='poi_busyness_forecast')
    op.drop_index('idx_forecast_level', table_name='poi_busyness_forecast')
    op.drop_table('poi_busyness_forecast')
    # ### end Alembic commands ###
