"""Add new date columns to saved_itineraries and itinerary_stops

Revision ID: a685b4a9286e
Revises: 9940cf707f25
Create Date: 2026-07-09 02:46:32.820412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a685b4a9286e'
down_revision: Union[str, Sequence[str], None] = '9940cf707f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerary_stops', sa.Column('visit_date', sa.Date(), nullable=False))
    op.add_column('itinerary_stops', sa.Column('hero_image_url', sa.Text(), nullable=False))
    op.drop_column('itinerary_stops', 'dates')
    op.add_column('saved_itineraries', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('saved_itineraries', sa.Column('end_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_itineraries', 'end_date')
    op.drop_column('saved_itineraries', 'start_date')
    op.add_column('itinerary_stops', sa.Column('dates', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('itinerary_stops', 'hero_image_url')
    op.drop_column('itinerary_stops', 'visit_date')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
