"""Change opening_hours_text and closest_subway varchar(100) to Text

Revision ID: bce1c9208d27
Revises: 9b0d8a6c958c
Create Date: 2026-06-23 20:45:03.221090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bce1c9208d27'
down_revision: Union[str, Sequence[str], None] = '9b0d8a6c958c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi', 'opening_hours_text',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('poi', 'closest_subway',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('poi_busyness_forecast', 'level',
               existing_type=postgresql.ENUM('quiet', 'moderate', 'busy', 'very_busy', name='busyness_level'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poi_busyness_forecast', 'level',
               existing_type=postgresql.ENUM('quiet', 'moderate', 'busy', 'very_busy', name='busyness_level'),
               nullable=True)
    op.alter_column('poi', 'closest_subway',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('poi', 'opening_hours_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
