"""Add column availability_mode

Revision ID: bf49552b5397
Revises: bce1c9208d27
Create Date: 2026-06-29 20:02:42.907759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf49552b5397'
down_revision: Union[str, Sequence[str], None] = 'bce1c9208d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi', sa.Column('availability_mode', sa.String(length=20), server_default=sa.text("'STRICT'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi', 'availability_mode')
    # ### end Alembic commands ###
