"""Check table creation

Revision ID: e921ec5c6db6
Revises: 1b414420d491
Create Date: 2026-06-20 01:25:23.025580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e921ec5c6db6'
down_revision: Union[str, Sequence[str], None] = '1b414420d491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_pois',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('poi_id', sa.BigInteger(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'poi_id')
    )
    op.alter_column('poi', 'slug',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('poi', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('poi', 'borough',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('poi', 'neighborhood',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('poi', 'hero_image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('poi', 'gallery_image_urls',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('poi', 'opening_hours_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('poi', 'google_place_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('poi', 'accessibility_labels',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.alter_column('poi', 'closest_subway',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('poi', 'map_embed_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('poi', 'map_external_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('poi', 'website_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.alter_column('poi', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('poi', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_index(op.f('idx_poi_borough'), table_name='poi')
    op.drop_index(op.f('idx_poi_geo'), table_name='poi')
    op.drop_index(op.f('idx_poi_tags'), table_name='poi', postgresql_using='gin')
    op.drop_index(op.f('idx_poi_type'), table_name='poi')
    op.drop_constraint(op.f('poi_google_place_id_key'), 'poi', type_='unique')
    op.drop_constraint(op.f('poi_slug_key'), 'poi', type_='unique')
    op.create_index(op.f('ix_poi_borough'), 'poi', ['borough'], unique=False)
    op.create_index(op.f('ix_poi_slug'), 'poi', ['slug'], unique=True)
    op.create_index(op.f('ix_poi_type'), 'poi', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_type'), table_name='poi')
    op.drop_index(op.f('ix_poi_slug'), table_name='poi')
    op.drop_index(op.f('ix_poi_borough'), table_name='poi')
    op.create_unique_constraint(op.f('poi_slug_key'), 'poi', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('poi_google_place_id_key'), 'poi', ['google_place_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_poi_type'), 'poi', ['type'], unique=False)
    op.create_index(op.f('idx_poi_tags'), 'poi', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_poi_geo'), 'poi', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('idx_poi_borough'), 'poi', ['borough'], unique=False)
    op.alter_column('poi', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('poi', 'phone',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'website_url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'map_external_url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'map_embed_url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'closest_subway',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'accessibility_labels',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('poi', 'google_place_id',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'opening_hours_text',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'gallery_image_urls',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    op.alter_column('poi', 'hero_image_url',
               existing_type=sa.String(length=2048),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'neighborhood',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('poi', 'borough',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('poi', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('poi', 'slug',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_table('saved_pois')
    # ### end Alembic commands ###
