"""switch token_version from users to user_session

Revision ID: f94b442e4071
Revises: 98f3ce1d730a
Create Date: 2026-06-19 22:40:07.794392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94b442e4071'
down_revision: Union[str, Sequence[str], None] = '98f3ce1d730a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('token_version', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('user_sessions', 'token_version')
    # ### end Alembic commands ###
