"""Add column time_slot to poi_busyness_forecast

Revision ID: f9c64de8290b
Revises: bf49552b5397
Create Date: 2026-06-30 00:28:03.718267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c64de8290b'
down_revision: Union[str, Sequence[str], None] = 'bf49552b5397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poi_busyness_forecast', sa.Column('time_slot', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('poi_busyness_forecast', 'time_slot')
    # ### end Alembic commands ###
