import json
from app.services.ai.base import LLMProvider
from app.services.ai.providers.gemini import GeminiProvider
from app.services.ai.providers.llama import LlamaProvider
from app.core.exceptions import LLMUnresponsiveError
from app.schemas.ai import ChatResponse

class FallbackProvider(LLMProvider):
    """
    LLM provider that falls back from Gemini to Llama when the primary
    provider is unavailable.
    """
    def __init__(self):
        self.primary = GeminiProvider()
        self.fallback = LlamaProvider()

    def extract_trip_parameters(self, prompt, last_message, trip_details):
        """
    Extract trip parameters using Gemini, falling back to Llama if necessary.

    Args:
        prompt: Current user prompt or conversation content.
        last_message: Most recent assistant message.
        trip_details: Current trip parameters.

    Returns:
        Extracted trip parameters from the available LLM provider.

    Raises:
        LLMUnresponsiveError: If both providers fail to respond.
    """
        if isinstance(prompt, list):
            prompt = json.dumps(prompt)

        try:
            return self.primary.extract_trip_parameters(prompt, last_message, trip_details)
        except LLMUnresponsiveError as e:
            self._fallback_message(e)

            try:
                return self.fallback.extract_trip_parameters(prompt, last_message, trip_details)
            except LLMUnresponsiveError as e:
                print(f"Error occurred during extraction: {e}")
                raise

    def generate_chat_response(self, history, summary, trip_details, conv_id, db, user):
        """
    Generate a conversational response using the primary or fallback LLM.

    Gemini is attempted first. If it is unavailable, the request is retried
    using Llama. If both providers fail, a user-friendly error response is
    returned.

    Args:
        history: Recent conversation history.
        summary: Conversation summary.
        trip_details: Current trip parameters.
        conv_id: Conversation identifier.
        db: Database session.
        user: Authenticated user identifier.

    Returns:
        A ChatResponse generated by an LLM provider or an error response if
        both providers are unavailable.
    """
        try:
            return self.primary.generate_chat_response(history, summary, trip_details, conv_id, db, user)
        except LLMUnresponsiveError as e:
            self._fallback_message(e)

            try:
                return self.fallback.generate_chat_response(history, summary, trip_details, conv_id, db, user)
            except LLMUnresponsiveError as e:
                print(f"Error occured during chat generation: {e}")
                return ChatResponse(
                    message="I'm having trouble responding right now. Please try again in a moment.",
                    ui_action=None,
                    itinerary=None,
                    save_to_history=False
                )
            
    def create_summary(self, history):
        """
    Create a conversation summary using the primary or fallback LLM.

    Args:
        history: Conversation history to summarise.

    Returns:
        A summary generated by the available LLM provider.

    Raises:
        LLMUnresponsiveError: If the fallback provider also fails.
    """
        try:
            return self.primary.create_summary(history)
        except LLMUnresponsiveError as e:
            self._fallback_message(e)

            return self.fallback.create_summary(history)
        
    def _fallback_message(self, e):
        print(f"Gemini failed: {e}")
        print("Switching to Llama")
            
